### ISSUE TITLE
No accessibility attributes used

### ISSUE THREAD

**Issue by ETNOL** [thoughtbot/empties#13]
These empties are an awesome tool for the web dev community. I'd like to see them also feature basic accessibility attributes and roles baked in as well since that aspect of development tends to be one of the last things on everyone's TODO lists. 

Here's a commit with role and attributes added to accordion for an example:
https://github.com/ETNOL/empties/commit/85cbbc8f9eb3e8ff225d1c6ba36bc32f4476229d

Let me know if there is any interest in adding this and I'll run with it.

**Comment by tysongach** [comment]
I’m closing this because this project will no longer be actively maintained. We are currently re-building Refills from the ground-up, with accessibility in mind.
