### ISSUE TITLE
`.button-icon` doesn't render as intended on firefox

### ISSUE THREAD

**Issue by creuter** [thoughtbot/empties#7]
flexed buttons don't play well on firefox.

<img width="1191" alt="screen shot 2015-12-11 at 10 43 59 am" src="https://cloud.githubusercontent.com/assets/2317604/11748044/53154da6-9ff4-11e5-9eb8-eba110452490.png">

**Comment by Magnus-G** [comment]
@creuter thanks for catching this. We should have caught this one earlier. Seems like flexbox doesn't work for buttons in Safari and Firefox so in this PR (https://github.com/thoughtbot/empties/pull/8) I have added a wrapper div inside of the button.

**Comment by Magnus-G** [comment]
This should be fixed per https://github.com/thoughtbot/empties/commit/4e95173bdc07244015807a9c913a7956156712df
